### ISSUE TITLE
How do the power calculations look? 

### ISSUE THREAD

**Issue by bpffjl** [GSA/2233-USWDS-Digital-Dashboard#1]
@jwbowers 

Can you have a look at 04. Analysis\scripts\2233-power-calcuations.rmd?

**Comment by jwbowers** [comment]
I left some comments in the code. I could not run it because I didn't have access to the oes libraries and the data. Still a bit confused and happy to screen share. Confusions included:

 - Why use `glm.nb` in a randomization experiment if aim is to estimate an ATE and/or learn about evidence against the null hypothesis that the true ATE=0?  To me seems unnecessary: provides coefs on a scale that must be converted to get an ATE and doesn't have the same unbiasedness guarantees of differences of means (as calculated by `lm_robust` for example)
 - Not sure that plotting coefs is helping us learn about power per se --- since power is the proportion of times a hypothesis of no effects is rejected when the true effect is non-zero.

**Comment by jwbowers** [comment]
I didn't close this issue but happy for you to do so if you want to take this conversation onto video etc.

**Comment by jwbowers** [comment]
Closing the issue after our discussion
